// <auto-generated />
using System;
using BuildingMaterialAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildingMaterialAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260409203751_AddCategoryImage")]
    partial class AddCategoryImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildingMaterialAPI.Models.BaoCao", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaBaoCao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCao"));

                    b.Property<string>("LoaiBaoCao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LoaiBaoCao");

                    b.Property<DateTime>("NgayBaoCao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayBaoCao");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int")
                        .HasColumnName("NguoiTao");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<string>("TenBaoCao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenBaoCao");

                    b.HasKey("MaBaoCao");

                    b.HasIndex("NguoiTao");

                    b.ToTable("BAOCAO");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.BaoGia", b =>
                {
                    b.Property<int>("MaBaoGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaBaoGia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoGia"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<int?>("KhachHangMaKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("MaBG")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaBG");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int")
                        .HasColumnName("MaKhachHang");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayLap");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TongTien");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaBaoGia");

                    b.HasIndex("KhachHangMaKhachHang");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("BAOGIA");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.CTBaoGia", b =>
                {
                    b.Property<int>("MaCTBG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTBG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTBG"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DonGia");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<int>("MaBaoGia")
                        .HasColumnType("int")
                        .HasColumnName("MaBaoGia");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("MaSanPham");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ThanhTien");

                    b.HasKey("MaCTBG");

                    b.HasIndex("MaBaoGia");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CTBAOGIA");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.CTFlashSale", b =>
                {
                    b.Property<int>("MaCTFlashSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTFlashSale");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTFlashSale"));

                    b.Property<int>("DaBan")
                        .HasColumnType("int")
                        .HasColumnName("DaBan");

                    b.Property<decimal>("GiaKhuyenMai")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GiaKhuyenMai");

                    b.Property<int>("MaFlashSale")
                        .HasColumnType("int")
                        .HasColumnName("MaFlashSale");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("MaSanPham");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<decimal>("PhanTramGiam")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PhanTramGiam");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.HasKey("MaCTFlashSale");

                    b.HasIndex("MaFlashSale");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CTFLASHSALE");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.CTHD", b =>
                {
                    b.Property<int>("MaCTHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTHD"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DonGia");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GiamGia");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int")
                        .HasColumnName("MaHoaDon");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("MaSanPham");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ThanhTien");

                    b.HasKey("MaCTHD");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CTHD");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.CTKhoHang", b =>
                {
                    b.Property<int>("MaCTKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTKho");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTKho"));

                    b.Property<int>("MaKhoHang")
                        .HasColumnType("int")
                        .HasColumnName("MaKhoHang");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("MaSanPham");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime?>("NgayNhapCuoi")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayNhapCuoi");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongNhap");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongTon");

                    b.Property<string>("ViTri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ViTri");

                    b.HasKey("MaCTKho");

                    b.HasIndex("MaKhoHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CTKHOHANG");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.CTPN", b =>
                {
                    b.Property<int>("MaCTPN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTPN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTPN"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DonGia");

                    b.Property<int>("MaPhieuNhap")
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuNhap");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("MaSanPham");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<int>("SoLuongDaNhan")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongDaNhan");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ThanhTien");

                    b.HasKey("MaCTPN");

                    b.HasIndex("MaPhieuNhap");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CTPN");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.CTPhieuDoiTra", b =>
                {
                    b.Property<int>("MaCTDT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTDT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTDT"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DonGia");

                    b.Property<int>("MaPhieuDT")
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuDT");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("MaSanPham");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ThanhTien");

                    b.HasKey("MaCTDT");

                    b.HasIndex("MaPhieuDT");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CTPHIEUDOITRA");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.CTPhieuTraHangNCC", b =>
                {
                    b.Property<int>("MaCTPT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTPT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTPT"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DonGia");

                    b.Property<int>("MaPhieuTra")
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuTra");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("MaSanPham");

                    b.Property<int>("SoLuongTra")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongTra");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ThanhTien");

                    b.HasKey("MaCTPT");

                    b.HasIndex("MaPhieuTra");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CT_PHIEUTRAHANG_NCC");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.ChiTietTraNo", b =>
                {
                    b.Property<int>("MaChiTietTN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaChiTietTN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietTN"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<int>("MaCongNo")
                        .HasColumnType("int")
                        .HasColumnName("MaCongNo");

                    b.Property<int?>("MaHoaDon")
                        .HasColumnType("int")
                        .HasColumnName("MaHoaDon");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MaNhanVien");

                    b.Property<int?>("MaPhieuNhap")
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuNhap");

                    b.Property<string>("MaTT")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaTT");

                    b.Property<DateTime>("NgayTT")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("PTTT")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PTTT");

                    b.Property<string>("SoGiaoDich")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SoGiaoDich");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SoTien");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaChiTietTN");

                    b.HasIndex("MaCongNo");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaPhieuNhap");

                    b.ToTable("CHITETTRANO");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.CongNo", b =>
                {
                    b.Property<int>("MaCongNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCongNo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCongNo"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<DateTime?>("HanThanhToan")
                        .HasColumnType("datetime2")
                        .HasColumnName("HanThanhToan");

                    b.Property<string>("LoaiCongNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LoaiCongNo");

                    b.Property<string>("MaCN")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaCN");

                    b.Property<int?>("MaHoaDon")
                        .HasColumnType("int")
                        .HasColumnName("MaHoaDon");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int")
                        .HasColumnName("MaKhachHang");

                    b.Property<int?>("MaNhaCungCap")
                        .HasColumnType("int")
                        .HasColumnName("MaNhaCungCap");

                    b.Property<int?>("MaPhieuNhap")
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuNhap");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<decimal?>("SoTienConLai")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SoTienConLai");

                    b.Property<decimal>("SoTienDaTra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SoTienDaTra");

                    b.Property<decimal>("SoTienNo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SoTienNo");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaCongNo");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("MaPhieuNhap");

                    b.ToTable("CONGNO");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.Coupon", b =>
                {
                    b.Property<int>("MaCoupon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCoupon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCoupon"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Code");

                    b.Property<decimal>("DonHangToiThieu")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DonHangToiThieu");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GiaTriGiam");

                    b.Property<decimal?>("GiamToiDa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GiamToiDa");

                    b.Property<string>("LoaiCoupon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("LoaiCoupon");

                    b.Property<string>("MaCP")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaCP");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayBatDau");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayKetThuc");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int>("SoLanDaDung")
                        .HasColumnType("int")
                        .HasColumnName("SoLanDaDung");

                    b.Property<int?>("SoLanDungToiDa")
                        .HasColumnType("int")
                        .HasColumnName("SoLanDungToiDa");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaCoupon");

                    b.ToTable("COUPON");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.FlashSaleNew", b =>
                {
                    b.Property<int>("MaFlashSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaFlashSale");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaFlashSale"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianBatDau");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianKetThuc");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDe");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaFlashSale");

                    b.ToTable("FLASHSALE");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHoaDon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GiamGia");

                    b.Property<int?>("MaCoupon")
                        .HasColumnType("int")
                        .HasColumnName("MaCoupon");

                    b.Property<string>("MaHD")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaHD");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int")
                        .HasColumnName("MaKhachHang");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MaNhanVien");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime?>("NgayGiao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayGiao");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayLap");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("PTTT")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PTTT");

                    b.Property<decimal?>("ThanhToan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ThanhToan");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TongTien");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaCoupon");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("HOADON");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKhachHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("HangThanhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HangThanhVien");

                    b.Property<string>("LoaiKH")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LoaiKH");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaSoThue");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("NguoiLienHe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NguoiLienHe");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Sdt");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenKH");

                    b.Property<decimal>("TongChiTieu")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TongChiTieu");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.ToTable("KHACHHANG");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.KhoHang", b =>
                {
                    b.Property<int>("MaKhoHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKhoHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoHang"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<string>("MaKho")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaKho");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenKho");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaKhoHang");

                    b.ToTable("KHOHANG");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.KhuyenMai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKhuyenMai");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuyenMai"));

                    b.Property<string>("HangThanhVien")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HangThanhVien");

                    b.Property<string>("MaKM")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaKM");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<decimal?>("PhanTramGiam")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PhanTramGiam");

                    b.Property<int>("SoLanDaDung")
                        .HasColumnType("int")
                        .HasColumnName("SoLanDaDung");

                    b.Property<int?>("SoLanToiDa")
                        .HasColumnType("int")
                        .HasColumnName("SoLanToiDa");

                    b.Property<decimal?>("SoTienGiam")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SoTienGiam");

                    b.Property<string>("TenKM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenKM");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianBatDau");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianKetThuc");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaKhuyenMai");

                    b.ToTable("KHUYENMAI");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.KhuyenMaiSanPham", b =>
                {
                    b.Property<int>("MaKMSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKMSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKMSP"));

                    b.Property<int>("MaKhuyenMai")
                        .HasColumnType("int")
                        .HasColumnName("MaKhuyenMai");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("MaSanPham");

                    b.HasKey("MaKMSP");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaSanPham");

                    b.ToTable("KHUYENMAI_SANPHAM");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("MaLoaiSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLoaiSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiSP"));

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaLoai");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenLoai");

                    b.HasKey("MaLoaiSP");

                    b.ToTable("LOAISANPHAM");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNhaCungCap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaCungCap"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaSoThue");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("NguoiLienHe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NguoiLienHe");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Sdt");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenNCC");

                    b.Property<string>("ThanhPho")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ThanhPho");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaNhaCungCap");

                    b.ToTable("NHACUNGCAP");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNhanVien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaNV");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Sdt");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenNV");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.NhanVienModuleQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CoTheSua")
                        .HasColumnType("bit")
                        .HasColumnName("CoTheSua");

                    b.Property<bool>("CoTheTao")
                        .HasColumnType("bit")
                        .HasColumnName("CoTheTao");

                    b.Property<bool>("CoTheXem")
                        .HasColumnType("bit")
                        .HasColumnName("CoTheXem");

                    b.Property<bool>("CoTheXoa")
                        .HasColumnType("bit")
                        .HasColumnName("CoTheXoa");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MaNhanVien");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Module");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<string>("TenModule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenModule");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("NHANVIEN_MODULE_QUYEN");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.NhatKy", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNhatKy");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("GiaTriCu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GiaTriCu");

                    b.Property<string>("GiaTriMoi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GiaTriMoi");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HanhDong");

                    b.Property<int?>("MaBanGhi")
                        .HasColumnType("int")
                        .HasColumnName("MaBanGhi");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    b.Property<string>("TenBang")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenBang");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGian");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("NHATKY");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.PhanQuyen", b =>
                {
                    b.Property<int>("MaPhanQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaPhanQuyen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanQuyen"));

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int")
                        .HasColumnName("MaQuyen");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int")
                        .HasColumnName("MaVaiTro");

                    b.HasKey("MaPhanQuyen");

                    b.HasIndex("MaQuyen");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("PHANQUYEN");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.PhieuDoiTra", b =>
                {
                    b.Property<int>("MaPhieuDT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuDT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuDT"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LyDo");

                    b.Property<string>("MaDT")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaDT");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int")
                        .HasColumnName("MaHoaDon");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MaNhanVien");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayDT")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayDT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<decimal?>("TongTienHoan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TongTienHoan");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaPhieuDT");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PHIEUDOITRA");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.PhieuGiaoHang", b =>
                {
                    b.Property<int>("MaPhieuGH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuGH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuGH"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<string>("MaGH")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaGH");

                    b.Property<int?>("MaHoaDon")
                        .HasColumnType("int")
                        .HasColumnName("MaHoaDon");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MaNhanVien");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayGiao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayGiao");

                    b.Property<DateTime?>("NgayGiaoDuKien")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayGiaoDuKien");

                    b.Property<DateTime?>("NgayGiaoThucTe")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayGiaoThucTe");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("NguoiGiao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NguoiGiao");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaPhieuGH");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PHIEUGIAOHANG");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.PhieuNhap", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuNhap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<int>("MaNhaCungCap")
                        .HasColumnType("int")
                        .HasColumnName("MaNhaCungCap");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MaNhanVien");

                    b.Property<string>("MaPN")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaPN");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime?>("NgayGiaoHang")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayGiaoHang");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayNhap");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<decimal?>("ThanhToan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ThanhToan");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TongTien");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PHIEUNHAP");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.PhieuTraHangNCC", b =>
                {
                    b.Property<int>("MaPhieuTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuTra");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuTra"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LyDo");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MaNhanVien");

                    b.Property<string>("MaPT")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaPT");

                    b.Property<int>("MaPhieuNhap")
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuNhap");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<DateTime>("NgayTra")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTra");

                    b.Property<decimal?>("TongTienHoan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TongTienHoan");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaPhieuTra");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaPhieuNhap");

                    b.ToTable("PHIEUTRAHANG_NCC");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaQuyen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("MaQ")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaQ");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("TenQ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenQ");

                    b.HasKey("MaQuyen");

                    b.ToTable("QUYEN");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSanPham");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<string>("AnhPhu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AnhPhu");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DonViTinh");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GiaBan");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GiaNhap");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<int>("MaLoaiSP")
                        .HasColumnType("int")
                        .HasColumnName("MaLoaiSP");

                    b.Property<string>("MaSP")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaSP");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<int>("MucTonToiThieu")
                        .HasColumnType("int")
                        .HasColumnName("MucTonToiThieu");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenSP");

                    b.Property<string>("ThuongHieu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ThuongHieu");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.Property<string>("XuatXu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("XuatXu");

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaLoaiSP");

                    b.ToTable("SANPHAM");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<DateTime?>("DangNhapCuoi")
                        .HasColumnType("datetime2")
                        .HasColumnName("DangNhapCuoi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("MaTK")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaTK");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int")
                        .HasColumnName("MaVaiTro");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MatKhau");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<DateTime?>("OTPExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("OTPExpiry");

                    b.Property<string>("ResetOTP")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResetOTP");

                    b.Property<string>("TenTK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenTK");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("TAIKHOAN");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaVaiTro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MaVT")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaVT");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("TenVT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenVT");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VAITRO");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.BaoCao", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.NhanVien", "NhanVien")
                        .WithMany("BaoCaos")
                        .HasForeignKey("NguoiTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.BaoGia", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.KhachHang", null)
                        .WithMany("BaoGias")
                        .HasForeignKey("KhachHangMaKhachHang");

                    b.HasOne("BuildingMaterialAPI.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.CTBaoGia", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.BaoGia", "BaoGia")
                        .WithMany("CTBaoGias")
                        .HasForeignKey("MaBaoGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingMaterialAPI.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaoGia");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.CTFlashSale", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.FlashSaleNew", "FlashSale")
                        .WithMany("CTFlashSales")
                        .HasForeignKey("MaFlashSale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingMaterialAPI.Models.SanPham", "SanPham")
                        .WithMany("CTFlashSales")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashSale");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.CTHD", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.HoaDon", "HoaDon")
                        .WithMany("CTHDs")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingMaterialAPI.Models.SanPham", "SanPham")
                        .WithMany("CTHDs")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.CTKhoHang", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.KhoHang", "KhoHang")
                        .WithMany("CTKhoHangs")
                        .HasForeignKey("MaKhoHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingMaterialAPI.Models.SanPham", "SanPham")
                        .WithMany("CTKhoHangs")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.CTPN", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("CTPNs")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingMaterialAPI.Models.SanPham", "SanPham")
                        .WithMany("CTPNs")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.CTPhieuDoiTra", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.PhieuDoiTra", "PhieuDoiTra")
                        .WithMany("CTPhieuDoiTras")
                        .HasForeignKey("MaPhieuDT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingMaterialAPI.Models.SanPham", "SanPham")
                        .WithMany("CTPhieuDoiTras")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuDoiTra");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.CTPhieuTraHangNCC", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.PhieuTraHangNCC", "PhieuTraHangNCC")
                        .WithMany("ChiTiet")
                        .HasForeignKey("MaPhieuTra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingMaterialAPI.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuTraHangNCC");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.ChiTietTraNo", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.CongNo", "CongNo")
                        .WithMany()
                        .HasForeignKey("MaCongNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuildingMaterialAPI.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietTraNos")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BuildingMaterialAPI.Models.NhanVien", "NhanVien")
                        .WithMany("ChiTietTraNos")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BuildingMaterialAPI.Models.PhieuNhap", "PhieuNhap")
                        .WithMany()
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CongNo");

                    b.Navigation("HoaDon");

                    b.Navigation("NhanVien");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.CongNo", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.HoaDon", "HoaDon")
                        .WithMany("CongNos")
                        .HasForeignKey("MaHoaDon");

                    b.HasOne("BuildingMaterialAPI.Models.KhachHang", "KhachHang")
                        .WithMany("CongNos")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BuildingMaterialAPI.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("CongNos")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BuildingMaterialAPI.Models.PhieuNhap", "PhieuNhap")
                        .WithMany()
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HoaDon");

                    b.Navigation("KhachHang");

                    b.Navigation("NhaCungCap");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.HoaDon", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("MaCoupon");

                    b.HasOne("BuildingMaterialAPI.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BuildingMaterialAPI.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Coupon");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.KhachHang", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("BuildingMaterialAPI.Models.KhachHang", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.KhuyenMaiSanPham", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("KhuyenMaiSanPhams")
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingMaterialAPI.Models.SanPham", "SanPham")
                        .WithMany("KhuyenMaiSanPhams")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.NhanVien", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("NhanVien")
                        .HasForeignKey("BuildingMaterialAPI.Models.NhanVien", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.NhanVienModuleQuyen", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.NhatKy", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("NhatKys")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.PhanQuyen", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.Quyen", "Quyen")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingMaterialAPI.Models.VaiTro", "VaiTro")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.PhieuDoiTra", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.HoaDon", "HoaDon")
                        .WithMany("PhieuDoiTras")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuildingMaterialAPI.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuDoiTras")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.PhieuGiaoHang", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.HoaDon", "HoaDon")
                        .WithMany("PhieuGiaoHangs")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BuildingMaterialAPI.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuGiaoHangs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HoaDon");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.PhieuNhap", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuildingMaterialAPI.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.PhieuTraHangNCC", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingMaterialAPI.Models.PhieuNhap", "PhieuNhap")
                        .WithMany()
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.SanPham", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoaiSP")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.TaiKhoan", b =>
                {
                    b.HasOne("BuildingMaterialAPI.Models.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.BaoGia", b =>
                {
                    b.Navigation("CTBaoGias");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.FlashSaleNew", b =>
                {
                    b.Navigation("CTFlashSales");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.HoaDon", b =>
                {
                    b.Navigation("CTHDs");

                    b.Navigation("ChiTietTraNos");

                    b.Navigation("CongNos");

                    b.Navigation("PhieuDoiTras");

                    b.Navigation("PhieuGiaoHangs");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.KhachHang", b =>
                {
                    b.Navigation("BaoGias");

                    b.Navigation("CongNos");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.KhoHang", b =>
                {
                    b.Navigation("CTKhoHangs");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.KhuyenMai", b =>
                {
                    b.Navigation("KhuyenMaiSanPhams");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.NhaCungCap", b =>
                {
                    b.Navigation("CongNos");

                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.NhanVien", b =>
                {
                    b.Navigation("BaoCaos");

                    b.Navigation("ChiTietTraNos");

                    b.Navigation("HoaDons");

                    b.Navigation("PhieuDoiTras");

                    b.Navigation("PhieuGiaoHangs");

                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.PhieuDoiTra", b =>
                {
                    b.Navigation("CTPhieuDoiTras");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.PhieuNhap", b =>
                {
                    b.Navigation("CTPNs");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.PhieuTraHangNCC", b =>
                {
                    b.Navigation("ChiTiet");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.Quyen", b =>
                {
                    b.Navigation("PhanQuyens");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.SanPham", b =>
                {
                    b.Navigation("CTFlashSales");

                    b.Navigation("CTHDs");

                    b.Navigation("CTKhoHangs");

                    b.Navigation("CTPNs");

                    b.Navigation("CTPhieuDoiTras");

                    b.Navigation("KhuyenMaiSanPhams");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang")
                        .IsRequired();

                    b.Navigation("NhanVien")
                        .IsRequired();

                    b.Navigation("NhatKys");
                });

            modelBuilder.Entity("BuildingMaterialAPI.Models.VaiTro", b =>
                {
                    b.Navigation("PhanQuyens");

                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
